language: node_js
node_js:
  - "6"
  - "7"
notifications:
  email: false
after_success:
  - npm i -g coveralls codeclimate-test-reporter
  - coveralls < coverage/lcov.info
  - codeclimate-test-reporter < coverage/lcov.info
